# Generated by Django 2.0.13 on 2020-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_with_appointment', models.IntegerField(default=0)),
                ('participants_without_appointment', models.IntegerField(default=0)),
                ('participant_visibility', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('invites', models.IntegerField(default=0)),
            ],
        ),
    ]
