# Generated by Django 4.1 on 2022-08-23 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiauth', '0008_auto_20200402_0951'),
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leader',
            name='api_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiauth.apiuser'),
        ),
    ]
