# Generated by Django 4.1 on 2022-08-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0002_leader_user_alter_leader_api_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='api_user',
        ),
    ]
