# Generated by Django 2.0.10 on 2019-02-11 10:10

import api.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('P', 'Password Reset'), ('M', 'Mailinglist unsubscribe'), ('C', 'Cancel appointments')], max_length=1)),
                ('expiration', models.DateTimeField(default=api.auth.models._get_date_2hours, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiauth.ApiUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
