# Generated by Django 2.0.13 on 2020-04-02 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0007_apiuser_is_ldap_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
