# Generated by Django 4.0.7 on 2023-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, verbose_name='agenda:closing:attribute:start')),
                ('end', models.DateTimeField(db_index=True, verbose_name='agenda:closing:attribute:end')),
                ('is_global', models.BooleanField(verbose_name='agenda:cosing:attribute:is_global')),
                ('comment', models.TextField(null=True, verbose_name='agenda:cosing:attribute:comment')),
            ],
        ),
    ]
