# Generated by Django 2.0.9 on 2018-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apiuser',
            name='groups',
            field=models.ManyToManyField(to='apiauth.ApiGroup'),
        ),
    ]
