# Generated by Django 2.0.10 on 2019-01-25 09:59

import api.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0003_apiuser_passwords_needs_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expiration', models.DateTimeField(default=api.auth.models._get_date_2hours, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiauth.ApiUser')),
            ],
        ),
    ]
