# Generated by Django 2.0.10 on 2019-02-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_participant_created'),
        ('apiauth', '0005_auto_20190211_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.Participant'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiauth.ApiUser'),
        ),
    ]
