# Generated by Django 2.0.13 on 2019-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0006_auto_20190211_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='is_ldap_account',
            field=models.BooleanField(default=False),
        ),
    ]
