# Generated by Django 4.0.7 on 2023-09-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invites', to='participants.participant')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_admin.surveydefinition')),
            ],
            options={
                'unique_together': {('survey', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(null=True)),
                ('page', models.IntegerField(default=0)),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey_admin.surveyinvite')),
            ],
        ),
    ]
