# Generated by Django 4.0.7 on 2023-03-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_auto_20220805_1151'),
        ('survey_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_invites', to='participants.participant')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_admin.surveydefinition')),
            ],
        ),
    ]
