# Generated by Django 4.0.7 on 2023-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
