# Generated by Django 4.0.7 on 2023-04-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_admin', '0003_surveyresponse_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyinvite',
            name='completed',
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='invite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey_admin.surveyinvite'),
        ),
    ]
