# Generated by Django 3.2.13 on 2022-07-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0026_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True, verbose_name='closing:attribute:start')),
                ('end', models.DateTimeField(db_index=True, verbose_name='closing:attribute:end')),
                ('is_global', models.BooleanField()),
                ('comment', models.TextField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.location')),
            ],
        ),
    ]
