# Generated by Django 3.2.13 on 2022-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
