# Generated by Django 2.2.12 on 2020-05-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='event',
            field=models.TextField(choices=[('LOGIN', 'login'), ('LOGOUT', 'logout'), ('UNCATEGORISED', 'uncategorised'), ('DOWNLOAD_DATA', 'download_data'), ('VIEW_DATA', 'view_data'), ('VIEW_SENSITIVE_DATA', 'view_sensitive_data'), ('DELETE_DATA', 'delete_data'), ('MODIFY_DATA', 'modify_data')]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user_type',
            field=models.TextField(blank=True, choices=[('SYSTEM', 'system'), ('ADMIN', 'admin'), ('LEADER', 'leader'), ('PARTICIPANT', 'participant'), ('UNKNOWN', 'unknown')], null=True),
        ),
    ]
