# Generated by Django 2.0.9 on 2018-12-14 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20181207_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaders.Leader', verbose_name='comment:attribute:leader'),
        ),
    ]
