# Generated by Django 2.0.9 on 2018-12-14 10:24

from django.db import migrations
import uil.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20181214_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=uil.core.fields.EncryptedTextField(
                verbose_name='comment:attribute:comment'),
        ),
    ]
