# Generated by Django 4.0.7 on 2023-09-05 14:35

import cdh.core.fields.encrypted_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', cdh.core.fields.encrypted_fields.EncryptedEmailField(verbose_name='participant:attribute:email')),
                ('name', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:name')),
                ('dyslexic_parent', cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('F', 'participant:attribute:dyslexic_parent:f'), ('M', 'participant:attribute:dyslexic_parent:m'), ('BOTH', 'participant:attribute:dyslexic_parent:both'), ('NO', 'participant:attribute:dyslexic_parent:no'), ('UNK', 'participant:attribute:dyslexic_parent:unk')], verbose_name='participant:attribute:dyslexic_parent')),
                ('birth_date', cdh.core.fields.encrypted_fields.EncryptedDateField(blank=True, null=True, verbose_name='participant:attribute:birth_date')),
                ('multilingual', cdh.core.fields.encrypted_fields.EncryptedBooleanField(blank=True, null=True, verbose_name='participant:attribute:multilingual')),
                ('phonenumber', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:phonenumber')),
                ('sex', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:sex')),
                ('email_subscription', cdh.core.fields.encrypted_fields.EncryptedBooleanField(default=False, verbose_name='participant:attribute:email_subscription')),
                ('birth_weight', cdh.core.fields.encrypted_fields.EncryptedIntegerField(null=True, verbose_name='participant:attribute:birth_weight')),
                ('pregnancy_weeks', cdh.core.fields.encrypted_fields.EncryptedIntegerField(null=True, verbose_name='participant:attribute:pregnancy_weeks')),
                ('pregnancy_days', cdh.core.fields.encrypted_fields.EncryptedIntegerField(null=True, verbose_name='participant:attribute:pregnancy_days')),
                ('phonenumber_alt', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:phonenumber_alt')),
                ('parent_name', cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:parent_name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='participant:attribute:created')),
                ('deactivated', models.DateTimeField(null=True, verbose_name='participant:attribute:deactivated')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', cdh.core.fields.encrypted_fields.EncryptedEmailField(verbose_name='secondary_email:attribute:email')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', cdh.core.fields.encrypted_fields.EncryptedTextField(verbose_name='criterion_answer:attribute:answer')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.criterion')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
        ),
    ]
