# Generated by Django 4.0.7 on 2023-10-30 11:13

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pregnancy_days',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pregnancy_weeks',
        ),
        migrations.AddField(
            model_name='participant',
            name='parent_first_name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:parent_first_name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='parent_last_name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:parent_last_name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='pregnancy_duration',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('LESS_THAN_37', 'participant:attribute:pregnancy_duration:less_than_37'), ('37_TO_42', 'participant:attribute:pregnancy_duration:37_to_42'), ('MORE_THAN_42', 'participant:attribute:pregnancy_duration:more_than_42')], null=True, verbose_name='participant:attribute:pregnancy_duration'),
        ),
        migrations.AddField(
            model_name='participant',
            name='tos_parent',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('M', 'participant:attribute:which_parent:m'), ('F', 'participant:attribute:which_parent:f'), ('BOTH', 'participant:attribute:which_parent:both'), ('NO', 'participant:attribute:which_parent:neither'), ('UNK', 'participant:attribute:which_parent:unk')], default='UNK', verbose_name='participant:attribute:dyslexic_parent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='birth_weight',
            field=cdh.core.fields.encrypted_fields.EncryptedIntegerField(choices=[('LESS_THAN_2500', 'participant:attribute:birth_weight:less_than_2500'), ('2500_TO_4500', 'participant:attribute:birth_weight:2500_to_4500'), ('MORE_THAN_4500', 'participant:attribute:birth_weight:more_than_4500')], null=True, verbose_name='participant:attribute:birth_weight'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dyslexic_parent',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('M', 'participant:attribute:which_parent:m'), ('F', 'participant:attribute:which_parent:f'), ('BOTH', 'participant:attribute:which_parent:both'), ('NO', 'participant:attribute:which_parent:neither'), ('UNK', 'participant:attribute:which_parent:unk')], verbose_name='participant:attribute:dyslexic_parent'),
        ),
        migrations.DeleteModel(
            name='SecondaryEmail',
        ),
    ]
