# Generated by Django 4.0.7 on 2023-10-31 13:35

import cdh.core.fields.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_participant_parent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cdh.core.fields.encrypted_fields.EncryptedCharField()),
            ],
        ),
    ]
