# Generated by Django 2.0.9 on 2018-12-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20181207_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='participant:attribute:birth_date'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='capable',
            field=models.BooleanField(default=True, verbose_name='participant:attribute:capable'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dyslexic',
            field=models.BooleanField(verbose_name='participant:attribute:dyslexic'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='participant:attribute:email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email_subscription',
            field=models.BooleanField(default=False, verbose_name='participant:attribute:email_subscription'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='handedness',
            field=models.TextField(blank=True, choices=[('left', 'participant:attribute:handedness:lefthanded'), ('right', 'participant:attribute:handedness:righthanded')], null=True, verbose_name='participant:attribute:handedness'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='language',
            field=models.TextField(verbose_name='participant:attribute:language'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='multilingual',
            field=models.NullBooleanField(verbose_name='participant:attribute:multilingual'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='participant:attribute:name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phonenumber',
            field=models.TextField(blank=True, null=True, verbose_name='participant:attribute:phonenumber'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sex',
            field=models.TextField(blank=True, choices=[('M', 'participant:attribute:sex:male'), ('F', 'participant:attribute:sex:female')], null=True, verbose_name='participant:attribute:sex'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='social_status',
            field=models.TextField(blank=True, choices=[('student', 'participant:attribute:social_role:student'), ('other', 'participant:attribute:social_role:other')], null=True, verbose_name='participant:attribute:social_status'),
        ),
        migrations.AlterField(
            model_name='secondaryemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='secondary_email:attribute:email'),
        ),
    ]
