# Generated by Django 4.0.7 on 2023-11-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='multilingual',
        ),
        migrations.AddField(
            model_name='participant',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='participants.language'),
        ),
    ]
