# Generated by Django 4.0.7 on 2023-11-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_remove_participant_multilingual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='languages',
        ),
        migrations.AddField(
            model_name='participant',
            name='languages',
            field=models.ManyToManyField(to='participants.language'),
        ),
    ]
