# Generated by Django 2.0.9 on 2018-12-18 12:27

from django.db import migrations
import cdh.core.fields.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_auto_20181214_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='handedness',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, choices=[('L', 'participant:attribute:handedness:lefthanded'), ('R', 'participant:attribute:handedness:righthanded')], null=True, verbose_name='participant:attribute:handedness'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='social_status',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, choices=[('S', 'participant:attribute:social_role:student'), ('O', 'participant:attribute:social_role:other')], null=True, verbose_name='participant:attribute:social_status'),
        ),
    ]
