# Generated by Django 4.0.7 on 2023-11-27 15:28

import cdh.core.fields.encrypted_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_participant_english_contact_participant_save_longer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', cdh.core.fields.encrypted_fields.EncryptedCharField(verbose_name='extradata:attribute:title')),
                ('created', cdh.core.fields.encrypted_fields.EncryptedDateTimeField(auto_now_add=True, verbose_name='extradata:attribute:created')),
                ('content', cdh.core.fields.encrypted_fields.EncryptedTextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
        ),
    ]
