# Generated by Django 4.0.7 on 2023-11-24 09:42

from django.db import migrations

languages = [
    "Arabisch",
    "Arabisch (Egyptisch)",
    "Arabisch (Marokkaans)",
    "Berbers",
    "Bulgaars",
    "Catalaans",
    "Chinees (Mandarijn)",
    "Chinees (Kantonees)  ",
    "Deens",
    "Duits",
    "Engels",
    "Frans",
    "Fries",
    "Grieks",
    "Hebreeuws",
    "Hindi",
    "Hindoestaans",
    "IJslands",
    "Indonesisch",
    "Italiaans",
    "Koerdisch",
    "Kroatisch",
    "Limburgs",
    "Macedonisch",
    "Nederlandse Gebarentaal (NGT)",
    "Oekraïens",
    "Papiaments",
    "Perzisch (Farsi)",
    "Pools",
    "Portugees",
    "Roemeens",
    "Russisch",
    "Sloveens",
    "Spaans",
    "Tsjechisch",
    "Turks",
    "Vlaams",
    "Afrikaans",
    "Zweeds",
]


def create_default_languages(apps, schema_editor):
    Language = apps.get_model("participants", "Language")
    for lang in languages:
        Language.objects.create(name=lang)


def undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0006_participant_english_contact_participant_save_longer"),
    ]

    operations = [migrations.RunPython(create_default_languages, undo)]
