# Generated by Django 4.0.7 on 2023-11-24 09:42

from django.db import migrations

languages = [
    "Nederlands",
    "Engels",
    "Duits",
    "Spaans",
    "Frans",
    "Italiaans",
    "Turks",
    "Fries",
    "Arabisch",
    "Russisch",
    "Chinees",
    "Grieks",
    "Portugees",
    "Hongaars",
]


def create_default_languages(apps, schema_editor):
    Language = apps.get_model("participants", "Language")
    for lang in languages:
        Language.objects.create(name=lang)


def undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0006_participant_english_contact_participant_save_longer"),
    ]

    operations = [migrations.RunPython(create_default_languages, undo)]
