# Generated by Django 4.0.7 on 2023-12-01 09:37

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_participant_english_contact_participant_save_longer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birth_weight',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('LESS_THAN_2500', 'participant:attribute:birth_weight:less_than_2500'), ('2500_TO_4500', 'participant:attribute:birth_weight:2500_to_4500'), ('MORE_THAN_4500', 'participant:attribute:birth_weight:more_than_4500')], null=True, verbose_name='participant:attribute:birth_weight'),
        ),
    ]
