# Generated by Django 4.0.7 on 2023-12-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_alter_participant_birth_weight'),
        ('participants', '0007_default_languages'),
    ]

    operations = [
    ]
