# Generated by Django 4.0.7 on 2023-12-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_extradata'),
        ('participants', '0008_merge_20231204_1114'),
    ]

    operations = [
    ]
