# Generated by Django 4.0.7 on 2023-12-08 11:02

import cdh.core.fields.encrypted_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_merge_0007_extradata_0008_merge_20231204_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='birth_weight',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dyslexic_parent',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email_subscription',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='english_contact',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='parent_first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='parent_last_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phonenumber_alt',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pregnancy_duration',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='save_longer',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tos_parent',
        ),
        migrations.CreateModel(
            name='ParticipantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:name')),
                ('sex', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:sex')),
                ('birth_date', cdh.core.fields.encrypted_fields.EncryptedDateField(blank=True, null=True, verbose_name='participant:attribute:birth_date')),
                ('birth_weight', cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('LESS_THAN_2500', 'participant:attribute:birth_weight:less_than_2500'), ('2500_TO_4500', 'participant:attribute:birth_weight:2500_to_4500'), ('MORE_THAN_4500', 'participant:attribute:birth_weight:more_than_4500')], null=True, verbose_name='participant:attribute:birth_weight')),
                ('pregnancy_duration', cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('LESS_THAN_37', 'participant:attribute:pregnancy_duration:less_than_37'), ('37_TO_42', 'participant:attribute:pregnancy_duration:37_to_42'), ('MORE_THAN_42', 'participant:attribute:pregnancy_duration:more_than_42')], null=True, verbose_name='participant:attribute:pregnancy_duration')),
                ('parent_first_name', cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:parent_first_name')),
                ('parent_last_name', cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:parent_last_name')),
                ('email', cdh.core.fields.encrypted_fields.EncryptedEmailField(verbose_name='participant:attribute:email')),
                ('phonenumber', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:phonenumber')),
                ('phonenumber_alt', cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:phonenumber_alt')),
                ('dyslexic_parent', cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('M', 'participant:attribute:which_parent:m'), ('F', 'participant:attribute:which_parent:f'), ('BOTH', 'participant:attribute:which_parent:both'), ('NO', 'participant:attribute:which_parent:neither'), ('UNK', 'participant:attribute:which_parent:unk')], verbose_name='participant:attribute:dyslexic_parent')),
                ('tos_parent', cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('M', 'participant:attribute:which_parent:m'), ('F', 'participant:attribute:which_parent:f'), ('BOTH', 'participant:attribute:which_parent:both'), ('NO', 'participant:attribute:which_parent:neither'), ('UNK', 'participant:attribute:which_parent:unk')], verbose_name='participant:attribute:dyslexic_parent')),
                ('save_longer', cdh.core.fields.encrypted_fields.EncryptedBooleanField(default=False, verbose_name='participant:attribute:save_longer')),
                ('english_contact', cdh.core.fields.encrypted_fields.EncryptedBooleanField(default=False, verbose_name='participant:attribute:english_contact')),
                ('email_subscription', cdh.core.fields.encrypted_fields.EncryptedBooleanField(default=False, verbose_name='participant:attribute:email_subscription')),
                ('languages', models.ManyToManyField(to='participants.language')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.participantdata'),
        ),
    ]
