# Generated by Django 4.0.7 on 2023-12-18 13:56

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_remove_participant_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantdata',
            name='sex',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(choices=[('M', 'participant:attribute:sex:male'), ('F', 'participant:attribute:sex:female'), ('UNK', 'participant:attribute:sex:prefer_not_to_answer')], null=True, verbose_name='participant:attribute:sex'),
        ),
    ]
