# Generated by Django 4.2.11 on 2024-04-30 13:55

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_alter_participantdata_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantdata',
            name='birth_date',
            field=cdh.core.fields.encrypted_fields.EncryptedDateField(blank=True, verbose_name='participant:attribute:birth_date'),
        ),
        migrations.AlterField(
            model_name='participantdata',
            name='birth_weight',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('LESS_THAN_2500', 'participant:attribute:birth_weight:less_than_2500'), ('2500_TO_4500', 'participant:attribute:birth_weight:2500_to_4500'), ('MORE_THAN_4500', 'participant:attribute:birth_weight:more_than_4500')], verbose_name='participant:attribute:birth_weight'),
        ),
        migrations.AlterField(
            model_name='participantdata',
            name='name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, verbose_name='participant:attribute:name'),
        ),
        migrations.AlterField(
            model_name='participantdata',
            name='parent_first_name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(verbose_name='participant:attribute:parent_first_name'),
        ),
        migrations.AlterField(
            model_name='participantdata',
            name='parent_last_name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(verbose_name='participant:attribute:parent_last_name'),
        ),
        migrations.AlterField(
            model_name='participantdata',
            name='phonenumber',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, verbose_name='participant:attribute:phonenumber'),
        ),
        migrations.AlterField(
            model_name='participantdata',
            name='pregnancy_duration',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('LESS_THAN_37', 'participant:attribute:pregnancy_duration:less_than_37'), ('37_TO_42', 'participant:attribute:pregnancy_duration:37_to_42'), ('MORE_THAN_42', 'participant:attribute:pregnancy_duration:more_than_42')], verbose_name='participant:attribute:pregnancy_duration'),
        ),
        migrations.AlterField(
            model_name='participantdata',
            name='sex',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(choices=[('M', 'participant:attribute:sex:male'), ('F', 'participant:attribute:sex:female'), ('UNK', 'participant:attribute:sex:prefer_not_to_answer')], verbose_name='participant:attribute:sex'),
        ),
    ]
