# Generated by Django 3.2.13 on 2022-08-05 09:51

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0012_auto_20220804_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='dyslexic',
        ),
        migrations.AddField(
            model_name='participant',
            name='dyslexic_parent',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(default=False, verbose_name='participant:attribute:dyslexic_parent'),
            preserve_default=False,
        ),
    ]
