# Generated by Django 4.2.11 on 2024-10-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0012_alter_participantdata_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantdata",
            name="languages",
            field=models.ManyToManyField(to="participants.language", verbose_name="participant:attribute:languages"),
        ),
    ]
