# Generated by Django 4.0.7 on 2023-06-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_auto_20220805_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='city',
        ),
    ]
