# Generated by Django 4.2.11 on 2025-02-28 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0013_alter_participantdata_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="participant:attribute:created"),
        ),
    ]
