# Generated by Django 4.2.11 on 2025-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0013_alter_participantdata_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="created",
            field=models.DateTimeField(verbose_name="participant:attribute:created"),
        ),
    ]
