# Generated by Django 4.0.7 on 2023-08-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0015_participant_deactivated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='capable',
        ),
    ]
