# Generated by Django 4.0.7 on 2023-07-27 14:10

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0015_participant_deactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dyslexic_parent',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(choices=[('F', 'participant:attribute:dyslexic_parent:f'), ('M', 'participant:attribute:dyslexic_parent:m'), ('BOTH', 'participant:attribute:dyslexic_parent:both'), ('NO', 'participant:attribute:dyslexic_parent:no'), ('UNK', 'participant:attribute:dyslexic_parent:unk')], verbose_name='participant:attribute:dyslexic_parent'),
        ),
    ]
