# Generated by Django 4.0.7 on 2023-08-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0017_remove_participant_capable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='language',
        ),
    ]
