# Generated by Django 4.0.7 on 2023-10-30 11:23

import cdh.core.fields.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='parent_name',
            new_name='parent_first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='pregnancy_days',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='pregnancy_weeks',
        ),
        migrations.AddField(
            model_name='signup',
            name='parent_last_name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='pregnancy_duration',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(null=True, verbose_name='participant:attribute:pregnancy_weeks'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='birth_weight',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(verbose_name='participant:attribute:birth_weight'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('NEW', 'signups:stats:new'), ('APPROVED', 'signups:stats:approved'), ('(REJECTED', 'signups:stats:rejected')], default='NEW', max_length=20),
        ),
    ]
