# Generated by Django 4.0.7 on 2023-01-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='Signup')
    ]
