# Generated by Django 4.0.7 on 2023-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signups', '0002_drop_signups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('parent_name', models.TextField()),
                ('city', models.TextField()),
                ('phonenumber', models.TextField()),
                ('phonenumber_alt', models.TextField()),
                ('email', models.TextField()),
                ('english_contact', models.BooleanField()),
                ('newsletter', models.BooleanField()),
                ('dyslexic_parent', models.BooleanField()),
                ('tos_parent', models.BooleanField()),
                ('speech_parent', models.BooleanField()),
                ('multilingual', models.BooleanField()),
                ('status', models.CharField(choices=[('NEW', 'signups:stats:new'), ('APPROVED', 'signups:stats:approved'), ('REJECTED', 'signups:stats:rejected')], default='NEW', max_length=20)),
            ],
        ),
    ]
