# Generated by Django 4.0.7 on 2023-11-14 09:47

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_remove_signup_multilingual_signup_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='save_longer',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(default=False),
            preserve_default=False,
        ),
    ]
