# Generated by Django 4.0.7 on 2023-01-27 10:16

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='birth_date',
            field=cdh.core.fields.encrypted_fields.EncryptedDateField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='city',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='dyslexic_parent',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='english_contact',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='multilingual',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='newsletter',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='parent_name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phonenumber',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phonenumber_alt',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='sex',
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='speech_parent',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(choices=[('NEW', 'signups:stats:new'), ('APPROVED', 'signups:stats:approved'), ('REJECTED', 'signups:stats:rejected')], default='NEW'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='tos_parent',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(),
        ),
    ]
