# Generated by Django 4.0.7 on 2023-01-30 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0004_alter_signup_birth_date_alter_signup_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
