# Generated by Django 4.2.11 on 2024-10-07 13:37

import cdh.core.fields.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signups", "0004_signup_save_longer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="participant:attribute:created"),
        ),
        migrations.AlterField(
            model_name="signup",
            name="name",
            field=cdh.core.fields.encrypted_fields.EncryptedCharField(verbose_name="participant:attribute:name"),
        ),
    ]
