# Generated by Django 4.2.11 on 2025-04-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signups", "0005_alter_signup_created_alter_signup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="reminder_sent",
            field=models.DateTimeField(null=True),
        ),
    ]
