# Generated by Django 4.0.7 on 2023-06-23 13:03

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0006_signup_email_confirmed_signup_link_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='speech_parent',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='tos_parent',
        ),
        migrations.AddField(
            model_name='signup',
            name='birth_weight',
            field=cdh.core.fields.encrypted_fields.EncryptedIntegerField(default=0, verbose_name='participant:attribute:birth_weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='pregnancy_days',
            field=cdh.core.fields.encrypted_fields.EncryptedIntegerField(default=0, verbose_name='participant:attribute:pregnancy_days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='pregnancy_weeks',
            field=cdh.core.fields.encrypted_fields.EncryptedIntegerField(default=0, verbose_name='participant:attribute:pregnancy_weeks'),
            preserve_default=False,
        ),
    ]
