# Generated by Django 2.0.9 on 2018-12-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0011_auto_20181211_1309'),
        ('participants', '0003_auto_20181211_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriumAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='criterium_answer:attribute:answer')),
                ('criterium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Criterium')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Participant')),
            ],
        ),
    ]
