# Generated by Django 2.0.10 on 2019-01-08 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_auto_20181218_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='participant:attribute:created'),
            preserve_default=False,
        ),
    ]
