# Generated by Django 2.0.10 on 2019-02-18 10:16

from django.db import migrations, models
import django.db.models.deletion
import cdh.core.fields.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0018_rename_criterium_criterion'),
        ('participants', '0007_participant_created'),
    ]

    operations = [
        migrations.RenameModel(
            'CriteriumAnswer', 'CriterionAnswer',
        ),
        migrations.RenameField(
            model_name='criterionanswer',
            old_name='criterium',
            new_name='criterion',
        ),
    ]
