# Generated by Django 2.0.13 on 2019-02-27 13:30

from django.db import migrations
import uil.core.fields.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_rename_criterium_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterionanswer',
            name='answer',
            field=uil.core.fields.encrypted_fields.EncryptedTextField(verbose_name='criterion_answer:attribute:answer'),
        ),
    ]
