# Generated by Django 2.2.12 on 2020-05-01 11:45

from django.db import migrations
import main.fields.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20190227_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='multilingual',
            field=main.fields.encrypted_fields.EncryptedBooleanField(blank=True, null=True, verbose_name='participant:attribute:multilingual'),
        ),
    ]
