# Generated by Django 2.2.16 on 2020-11-26 13:11

from django.db import migrations
import uil.core.fields.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_auto_20200501_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='sex',
            field=uil.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:sex'),
        ),
    ]
