# Generated by Django 3.2.13 on 2022-08-04 08:13

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_auto_20201126_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='handedness',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='social_status',
        ),
        migrations.AddField(
            model_name='participant',
            name='birth_weight',
            field=cdh.core.fields.encrypted_fields.EncryptedIntegerField(null=True, verbose_name='participant:attribute:birth_weight'),
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:city'),
        ),
        migrations.AddField(
            model_name='participant',
            name='parent_name',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:parent_name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phonenumber_alt',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(blank=True, null=True, verbose_name='participant:attribute:phonenumber_alt'),
        ),
        migrations.AddField(
            model_name='participant',
            name='pregnancy_days',
            field=cdh.core.fields.encrypted_fields.EncryptedIntegerField(null=True, verbose_name='participant:attribute:pregnancy_days'),
        ),
        migrations.AddField(
            model_name='participant',
            name='pregnancy_weeks',
            field=cdh.core.fields.encrypted_fields.EncryptedIntegerField(null=True, verbose_name='participant:attribute:pregnancy_weeks'),
        ),
    ]
