# Generated by Django 2.0.13 on 2019-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190122_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ldap_account',
            field=models.BooleanField(default=False),
        ),
    ]
