# Generated by Django 2.0.13 on 2019-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_ldap_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_ldap_account',
            field=models.BooleanField(default=False, verbose_name='user:is_ldap_account'),
        ),
    ]
