# Generated by Django 2.0.9 on 2018-11-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiauth', '0002_auto_20181115_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phonenumber', models.TextField()),
                ('api_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiauth.ApiUser')),
            ],
        ),
    ]
