# Generated by Django 4.0 on 2022-08-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_create_user_groups'),
        ('leaders', '0003_remove_leader_api_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
