# Generated by Django 2.0.9 on 2018-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supreme_admin',
            field=models.BooleanField(default=False),
        ),
    ]
