# Generated by Django 4.2.11 on 2025-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_support",
            field=models.BooleanField(default=False, verbose_name="user:attribute:is_support"),
        ),
    ]
