# Generated by Django 2.0.10 on 2019-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_supreme_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_supreme_admin',
            field=models.BooleanField(default=False, verbose_name='user:is_supreme_admin'),
        ),
    ]
