# Generated by Django 4.0.7 on 2022-12-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_supreme_admin',
        ),
    ]
