# Generated by Django 4.0.7 on 2023-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
