# Generated by Django 3.2.13 on 2022-07-01 08:09

from django.db import migrations


def create_groups(apps, schema):
    ApiGroup = apps.get_model('apiauth', 'ApiGroup')
    ApiGroup.objects.create(name='leader')
    ApiGroup.objects.create(name='participant')


def drop_groups(apps, schema):
    ApiGroup = apps.get_model('apiauth', 'ApiGroup')
    ApiGroup.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_first_name'),
    ]

    operations = [
        migrations.RunPython(create_groups, drop_groups)
    ]
