# Generated by Django 4.0.7 on 2023-01-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_user_is_supreme_admin'),
        ('main', '0007_user_name_user_phonenumber'),
    ]

    operations = [
    ]
