# Generated by Django 4.0.7 on 2023-08-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ldap_account',
        ),
    ]
