# Generated by Django 4.0.7 on 2023-09-05 14:35

import cdh.core.fields.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', cdh.core.fields.encrypted_fields.EncryptedTextField(verbose_name='comment:attribute:comment')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='comment:attribute:datetime')),
                ('system_comment', models.BooleanField(default=False, verbose_name='comment:attribute:datetime')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
