# Generated by Django 2.0.9 on 2018-11-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0002_experiment_excluded_experiments'),
        ('participants', '0001_initial'),
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Experiment')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaders.Leader')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Participant')),
            ],
        ),
    ]
