# Generated by Django 2.0.9 on 2018-11-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='comment:attribute:datetime'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='comment:attribute:comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Experiment', verbose_name='comment:attribute:experiment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaders.Leader', verbose_name='comment:attribute:leader'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Participant', verbose_name='comment:attribute:participant'),
        ),
    ]
