# Generated by Django 2.0.9 on 2018-12-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20181214_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='comment:attribute:datetime'),
        ),
    ]
