# Generated by Django 4.0.7 on 2023-01-09 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0009_remove_comment_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='comment:attribute:leader'),
        ),
    ]
