# general integration tests for the combined application
name: Integration tests

on:
  push:
    branches: [ develop, main, ]
  pull_request:
    branches: [ develop, main, ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      max-parallel: 2
      matrix:
        node-version: [16]
        python-version: ['3.10']

    steps:
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libldap2-dev libsasl2-dev libssl-dev gettext poppler-utils poppler-data libpoppler-cpp-dev
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lab/requirements.txt
          pip install -r lab/requirements-dev.txt
          pip install pytest
      - name: Compile 18n
        run: |
          cd lab
          python manage.py compilemessages
          cd ../parent
          python manage.py compilemessages
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'babex-vue/package-lock.json'
      - name: Install node deps
        run: |
          cd babex-vue
          npm ci
      - name: Lint Vue app
        run: |
          cd babex-vue
          npm run lint
      - name: Build Vue app
        if: always()  # continue with build when linting fails
        run: |
          cd babex-vue
          npm run dev
      - name: Integration tests
        run: |
          cd integration_tests
          pytest
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: pytest_logs
          path: ${{ matrix.app }}/integration_tests/latest_logs/
